[tasks.run]
description = "upgrade all"
run = "brew upgrade && mise upgrade"    

[tools]
fd = "latest"
bat = "latest"
bottom = "latest"
gh = "latest"
lsd = "latest"
ripgrep = "latest"
starship = "latest"
fzf = "latest"

[tools."github:alacritty/alacritty"]
version = "latest"
[tools."github:alacritty/alacritty".platforms]
macos-arm64 = {asset_pattern = "Alacritty-v*.dmg"}
